# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Degree360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(choices=[(0, 'MultiChoice'), (1, 'Open')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
