# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Degree360', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackprovider',
            unique_together=set([('survey', 'email')]),
        ),
    ]
