# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Degree360', '0002_auto_20170911_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multichoiceanswer',
            unique_together=set([('feedback_provider', 'question', 'answer')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionsection',
            unique_together=set([('survey', 'description')]),
        ),
    ]
