# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Degree360', '0003_auto_20170922_2136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multichoiceanswer',
            unique_together=set([('feedback_provider', 'question')]),
        ),
    ]
